{
 "title": "AAVE loop",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30m",
 "panels": [
  {
   "title": "Health Factor",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(scale(contractMonitor.*.production.task.*.getPositionData.healthFactor, 1e-18), '10m', 'min', false), 4)"
    }
   ]
  },
  {
   "title": "Balance Rewards",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "health factor" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(scale(contractMonitor.*.production.task.*.getBalanceReward.val, 1e-18), '10m', 'min', false), 4)"
    }
   ]
  },
  {
   "title": "Rewards",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "health factor" }
   ],
   "targets": [
    {
     "target": "aliasByNode(averageBelow(summarize(scale(contractMonitor.*.production.task.*.*.val, 1e-18), '10m', 'min', false), 5), 5, 4)"
    }
   ]
  }
 ]
}